"use client";

import Image from "next/image";
import { useState, useEffect } from "react";

const images = [
  "/images/hero-clinic.png",
  "/images/clinic-exterior.png",
  "/images/clinic_reception_interior_1773080692661.png", // I should make sure these paths are correct or use the generated ones
];

const carouselImages = [
  { src: "/images/cabinet/treatment-room.png", alt: "Salle de traitement moderne" },
  { src: "/images/cabinet/scanner-3d.png", alt: "Scanner dentaire 3D" },
  { src: "/images/cabinet/hallway.png", alt: "Couloir de la clinique" },
  { src: "/images/cabinet/consultation.png", alt: "Zone de consultation" },
  { src: "/images/cabinet/itero-scan.png", alt: "Empreinte numérique iTero" },
];

// Actually, I should use the images I generated if possible, but I need to copy them to public first.
// I'll use placeholder-like styling for now or just high-quality Unsplash for reliability in this demo.
// Re-planning: I'll use the ones I generated by referencing their eventual public paths.

export default function CabinetCarousel() {
  const [currentIndex, setCurrentIndex] = useState(2);

  const nextSlide = () => {
    setCurrentIndex((prev) => (prev + 1) % carouselImages.length);
  };

  const prevSlide = () => {
    setCurrentIndex((prev) => (prev - 1 + carouselImages.length) % carouselImages.length);
  };

  return (
    <section className="bg-white py-24 overflow-hidden">
      <div className="relative w-full max-w-[1400px] mx-auto px-4 sm:px-6 lg:px-8">
        <div className="relative flex items-center justify-center gap-4 sm:gap-8 min-h-[500px] sm:min-h-[600px]">
          {carouselImages.map((image, index) => {
            let position = index - currentIndex;
            if (position < -2) position += carouselImages.length;
            if (position > 2) position -= carouselImages.length;

            const isActive = position === 0;
            const isVisible = Math.abs(position) <= 2;

            if (!isVisible) return null;

            return (
              <div
                key={index}
                onClick={() => setCurrentIndex(index)}
                className={`absolute transition-all duration-700 ease-in-out cursor-pointer overflow-hidden rounded-[2rem] sm:rounded-[4rem] shadow-2xl ${
                  isActive
                    ? "z-30 w-[70%] sm:w-[45%] aspect-[3/4] scale-110 opacity-100"
                    : "z-10 w-[35%] sm:w-[25%] aspect-[3/4] opacity-40 scale-90 grayscale-[50%]"
                }`}
                style={{
                  transform: `translateX(${position * 60}%) scale(${isActive ? 1.1 : 0.9})`,
                }}
              >
                <Image
                  src={image.src}
                  alt={image.alt}
                  fill
                  className="object-cover"
                />
              </div>
            );
          })}
        </div>

        {/* Navigation Dots */}
        <div className="mt-16 flex justify-center gap-3">
          {carouselImages.map((_, index) => (
            <button
              key={index}
              onClick={() => setCurrentIndex(index)}
              className={`w-2.5 h-2.5 rounded-full transition-all duration-300 ${
                index === currentIndex ? "bg-dark-taupe w-8" : "bg-dark-taupe/20"
              }`}
              aria-label={`Go to slide ${index + 1}`}
            />
          ))}
        </div>
      </div>
    </section>
  );
}
